# Stage 1: Build
FROM node:22-alpine AS builder 
WORKDIR /app

# Copy package and tsconfig files
COPY package*.json tsconfig.json tsconfig.base.json ./

# Install dependencies
RUN npm install

# Copy Prisma schema into expected folder
COPY src/database/prisma ./prisma

# Generate Prisma client
RUN npx prisma generate --schema=./prisma/schema.prisma

# Copy source code
COPY src ./src

# Build TypeScript
RUN npm run build

# Stage 2: Runtime
FROM node:22-alpine AS runtime
WORKDIR /app

# Copy only the necessary files from builder
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY package*.json ./

# Expose port and run
EXPOSE 7777
CMD ["node", "dist/index.js"]
