services:
  logconsumer:
    build:
      context: ./logconsumer
      dockerfile: Dockerfile
    container_name: logconsumer
    env_file:
      - ./logconsumer/.env
    ports:
      - "7777:7777"
    depends_on:
      - kafka
      - elasticsearch
    environment:
      KAFKA_BROKER: kafka:9092
      ELASTICSEARCH_URL: http://elasticsearch:9200

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: elasticsearch-prod
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
